### PR TITLE
Complete Performance and Appearance Revamp

### LINKED ISSUE #50: Add a Buffer to the viewport Iframe Lazy loader
Perhaps use a buffer, so the iframe begins to load about 200 pixles below the viewport

### LINKED ISSUE #54: Ctrl+Enter Disable Imbed
Ctrl+Enter when creating a new link should make the imbed disabled, and just have a plain link.
Perhaps when pasting, it could be ctrl+shift+v.

### LINKED ISSUE #74: Some google images title scraper 404
On google images, title scraper 404s and gives a bad title.

### LINKED ISSUE #85: If Trying to find an object while it is being embeded or grabbing the title, the app embedding crashes
As the title says, I was searching for something while also trying to force things to load, and The embedding stop because the javascript crashed. Log:

TypeError: Cannot set property 'innerHTML' of null
    at links.js:95
    at processQueue (angular.js:14745)
    at angular.js:14761
    at Scope.$eval (angular.js:15989)
    at Scope.$digest (angular.js:15800)
    at Scope.$apply (angular.js:16097)
    at done (angular.js:10546)
    at completeRequest (angular.js:10744)
    at XMLHttpRequest.requestLoaded (angular.js:10685)

### LINKED ISSUE #112: Deleting a card sometimes stops all grid operations

### LINKED ISSUE #113: Render Thread Lock - Grid re-sort
Everytime a card render is triggered, the render thread locks up. This stops scrolling and all interaction for a few seconds in Chrome and Firefox (I tested under)

### LINKED ISSUE #114: Render Thread Lock - Loading more links...
Loading more links at bottom of page renderlocks

### LINKED ISSUE #116: Modify Gridify for Parallel Support

### LINKED ISSUE #119: Label List - Count of Dumps Under Label
Tools (6)
Music (20)

Simple count of all dumps under a label.

### LINKED ISSUE #121: Label List - Label Open Mechanics
Instead of performing a search, opening a label should add another filter.

This way, when someone opens a label, they can still search inside of the results.

In addition, this prevents some bugs where the search matches more than just the label title.

### PR DESCRIPTION
**Pull request by julianpoy**
Closes #121 
Closes #119
Closes #116
Closes #114 
Closes #113 
Closes #112 
Closes #85 
Closes #74 
Closes #54 
Closes #50

The original focus of this pull request was performance, however it became more.

Gridify simply wasn't working for performance, and there was simply no way to make it perform as quick as it should.

Instead, I've ditched Gridify and moved to a 100% flexbox solution. All cards are now standard height, and embeds are handled completely differently.

In addition, I've added a catalog/list of tags, a prime feature requested by users (ahem alexis).

### CODE REVIEW

**Comment by torch2424** [comment]
Oh nice! I dont know If I am allowed to pull this in, but Thank you for doing this :D

**Comment by julianpoy** [comment]
Fook meh. I have no time. I started working on this but never came back :'(

**Comment by julianpoy** [comment]
Pulling this in would make a merge commit, thus I think you'd better not.

I have some more work to do on this before its ready, at which point I'll have you test it and I'll pull it in. Sound good?

**Comment by torch2424** [comment]
@julianpoy Sounds great 

Also, could you make an issue for me saying we should check this out after my internship?

http://michalsnik.github.io/aos/

**Comment by torch2424** [comment]
Ayyyeeee New Changes!

**Comment by julianpoy** [comment]
These changes are live at https://dev.kondeo.com/linkdrops

**Comment by julianpoy** [comment]
This has been closed. I will be continuing this featureset in a separate repository.

**Pull request closed without merging**
