### PR TITLE
Add providers

### LINKED ISSUE #9: Add support for alot of big media websites
Youtube - Finished
Vimeo - FInished
Spotify - Finished
Bandcamp - Finished
Soundcloud - Finished
Imgur (Use imgurs api, it'd be best to not run up our free embedly)

This list is growing, and we should look many places and try to support over a wide array of websites

### LINKED ISSUE #21: Work a little bit more on Responsiveness
Everything scales beautfully on mobile.

However, bandcamp iframes break the card panels.

Video iframes are not responsize, and are very tall, but not much width for the thumbnail.

Performance is MUCH MUCH MUCH MUCH MUCH better than I had anticipated, and the lazy loading does a ton of help. but it could always be a little bit better.

### PR DESCRIPTION
**Pull request by torch2424**
closes #9 
closes #21 

This simply updates the supported embeddable webistes as seen in the wiki: https://github.com/torch2424/link-drops/wiki/Supported-Providers

Also, I frames were really non responsive, so this has been fixed, and works much better now!

Lastly, Embedly has been removed completely to save us some cash.

---
## HOWEVER

I may have introduced a bug, where a div needs to be clicked in order for the in-viewport to work. This may be something regarding it's css I added. As I tried removing the html and it did not fix. My computer was acting very wonky the day I discovered this. But please do not pull if the problem persists.

EDIT: This is not because of this pull request, I am actually having the problem even on the current live production at linkdrops.com. As stated above it may just be my device, however I created an issue for it: #58

### CODE REVIEW

**Comment by julianpoy** [comment]
In review

**Comment by julianpoy** [comment]
--- Sizing ---
Youtube videos do not size properly.
Instagram imbeds do not size properly.
Wikipedia imbeds do not size properly.
Twitter imbeds do not size properly.
Gist imbeds do not size properly.
Kickstarter imbeds do not size properly.
--- Claimed to work in Wiki ---
Amazon imbeds do not show up.
Vine imbeds do not show up.
Vimeo imbeds do not show up.
Spotify imbeds do not show up.
--- Used to work, now broken ---
Soundcloud imbeds are no longer working.

Looks like this pull is far from ready, or the wiki should be updated. Either one.

**Comment by torch2424** [comment]
@julianpoy 

--Sizing--
I thought they looked fine being portrait, but I'll go and add css for them individually to fix that.

--Claimed to work in Wiki--

Are you sure it's not because of what I said in my OP.I tested all of these right now, and they all worked beautiful. Note for ones that did not start in the viewport, I had to click the link, and then go back for them to show up. It is a bug that is not because of this branch that was introduced into master, can needs to be fixed.

--Used to work, now broken --

Again, see the OP. I tested this working just fine.

P.S If you are refferring to any of the embeds being cut off, I can add a border for them. As some of the mebeds will display ALOT of content, so I added a max height and width to make things manageable

P.S.S Vine got blocked from no embed it seems. I tested it working before, But I think they just wanted to make me look dump :p My apologies on that one

P.S.S.S Vimeo acidentally became vine twice. That one was entirely my bad. My apologies

Last P.S Just spent the last hour re-testing, Again, please notice the bug I posted. Everything shall be fine and I will comment when I finishing styling

**Comment by torch2424** [comment]
Finished now is EXCELLENT to pull in . EXTENSIVELY tested on my end. going to work on that bug now, in a new branch

**Comment by torch2424** [comment]
I fixed the bug I am referring to in another branch. twas a super easy fix, and I'll do the offest thingy you wanted while I am at it :)

Actually for the offset i'll need the branches to be pulled in

See #59 for the bug fix

**Comment by julianpoy** [comment]
#59 has been merged. Can you pull master into this branch, so that I can retest and verify all is well?
I want to make sure the bug I experienced isn't still lurking somewhere.

**Comment by torch2424** [comment]
Pulled in yo!

**Comment by julianpoy** [comment]
Coolio. Will check this out and pull in if it works :)

**Comment by julianpoy** [comment]
--- Sizing ---
Youtube videos do not size properly.
--- Claimed to work in Wiki ---
Amazon imbeds do not show up.
Spotify imbeds do not show up.
--- Used to work, now broken ---
Soundcloud imbeds are no longer working.

An example containing all that are broken:
https://www.dropbox.com/s/ofg034lxrxnwd66/Screenshot%202015-09-20%2009.34.35.png?dl=0

**Comment by torch2424** [comment]
@julianpoy We are going to have to do this in person. I tested this for like 2 hours, and got everything working. something is up with your machine, everything wors on all of mines. And I dont quite understand what's wrong with the youtube size

**Comment by julianpoy** [comment]
Did you see the screenshot?

**Comment by julianpoy** [comment]
These are the links I used:
https://soundcloud.com/oftheothertime/moments-in-takyon
https://open.spotify.com/track/18sbrkncm1bTPAv2pzsVGM
http://www.amazon.com/Schleich-14601-Giant-Turtle/dp/B001O2QW9G/ref=sr_1_1?ie=UTF8&qid=1442766332&sr=8-1&keywords=turtle
https://www.youtube.com/watch?v=A_7phE0RtbU

**Comment by torch2424** [comment]
The soundcloud song can't be embedded period. If you try soundcloud doesnt allow you, did you perhaps turn off embedding for that song?

**Comment by torch2424** [comment]
Yes I saw the screenshot. Could you please explain to me the youtube thingy? and the spotify did work, just with play.spotify, not open.spotify, so I'll add that too

**Comment by torch2424** [comment]
I wanted to avoid using just amazon.com/ , so I did some more deep linking, but you seemed to find a place where you can avoid /gp/product.

**Comment by julianpoy** [comment]
Most products I just looked at dont use /gp/product. Perhaps because Im using prime?

**Comment by julianpoy** [comment]
As for youtube: the box is far off-center

**Comment by torch2424** [comment]
@julianpoy perhaps, but everything should be fixed now!

**Comment by torch2424** [comment]
Yo, added some more centering to the youtube thing. but honestly, I cant replicate it

**Comment by julianpoy** [comment]
I notice that you replaced play.spotify.com with open.spotify.com. We need to handle both.

**Comment by julianpoy** [comment]
Honestly we need to be able to detect a lot of possibilities. We are going to be putting it out to users who will not be careful about what they paste

**Comment by torch2424** [comment]
It does handle both. the code is currently:

```
<div class = "embed"
            ng-if = "(dump.content.indexOf('https://play.spotify.com/') > -1)
                || (dump.content.indexOf('https://open.spotify.com/') > -1)"
```

**Comment by torch2424** [comment]
and I got the youtube thing, its the card size that's acting weird with the column thingy

**Comment by julianpoy** [comment]
I fixed it.

**Comment by torch2424** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by torch2424** [comment]
I made width auto hahaha

**Comment by julianpoy** [comment]
Width auto will inherit width 90%, therefore duplicated code

**Comment by julianpoy** [comment]
Whats up with soundcloud?

**Comment by torch2424** [comment]
okay cool. Well is everything working for you?

**Comment by torch2424** [comment]
screenshot from 2015-09-20 11 33 11

Does your song settings match this? I think that song cant be embedded because when you uploaded the song, you didnt want people to be able to embed it

**Comment by julianpoy** [comment]
The thing is, on master, my song embeds.

**Comment by torch2424** [comment]
Okay, then we're going to have to use the soundcloud api then. Right now I'm doing homework, I'll switch it back to the soundcloud api from master

**Comment by julianpoy** [comment]
Oh gotcha, sounds good.

**Comment by torch2424** [comment]
I switched back to the soundcloud api to make your song work <3

**Comment by julianpoy** [comment]
Woo!

**Pull request merged**
