### PR TITLE
Fixed the large scaling of the app!

### PR DESCRIPTION
**Pull request by torch2424**
As the title says, fonts smaller and spacing muuuuccchhh better!

screenshot from 2015-11-15 19 55 50

screenshot from 2015-11-15 19 55 57

### CODE REVIEW

**Comment by torch2424** [comment]
Pictures were of two different chrome zooms :) first is 125% and second is 100%

**Comment by julianpoy** [comment]
Sweeeet. Lemme test this out right quick

**Comment by julianpoy** [comment]
Lel @ the branchname

**Comment by julianpoy** [comment]
Hmm, this might be completely unrelated (I think it is), but heres a bug...
https://www.dropbox.com/s/65ptcicldwbh1h5/Screenshot%202015-11-15%2020.01.49.png?dl=0

**Comment by torch2424** [comment]
Yeah it's unrelated, I need to figure out how to fix that, it's like whenever the link doesnt have a title, or it's still loading it will do that. probably just gotta do some css. could you make an issue for us to tackle for that?

**Pull request merged**
