### PR TITLE
Directive columns

### LINKED ISSUE #51: Cards Need horizontal order with columns
Cards organize themselves vertically, but need to be organized horizontally

### LINKED ISSUE #69: Youtube embeds lose control once clicked
If you press play on a youtube embed, your mouse is no longer recognized by it, and it acts funny

### PR DESCRIPTION
**Pull request by torch2424**
closes #51 
closes #69

This finally solves the dreaded issue. However, performance is slightly worse, if not the same, and made an easy to adjust and use directive :) please test, and see an example below!

untitled recording 5

### CODE REVIEW

**Comment by julianpoy** [comment]
HOLY SHEIT

**Comment by torch2424** [comment]
@julianpoy I know right, this was so much work :'D

**Comment by torch2424** [comment]
@julianpoy But lease wait until I finish my angular material branch before pulling the have grid layout directive built in so we may not need this :o Also I removed Jquery, I found out its required by bootstrap sass :ooooo

**Comment by julianpoy** [comment]
Wut... Bootstrap sass? So we cant have sass or just bootstrap?
Also I saw I wasn't assigned so I didn't pull it in :)

**Comment by torch2424** [comment]
Yeah thank you! I knew you wouldnt! And yes whenever we generate yeoman from now on, say no bootstrap. What I'm doing the angular material branch is I'm using bootstraps custom downloader to get only the bootstrap css I need for the navbar, and I did all the collapsing js myself to avoid jquery. It's quite a lengthy alternative, but It should help the page tons

**Comment by julianpoy** [comment]
Honestly either of us can recode the nav without much trouble. Theres not much to it.

**Comment by torch2424** [comment]
After doing some Angular material research, they're grid list isn't as dynamic as it made itself seem in the demo. Our elements must already have a pretermined row and column span, which we would have to calculate, I say we simply pull this in, after some testing of course, that way we have easy responsive grid based directive that does what we need it to do!

**Comment by torch2424** [comment]
@julianpoy Please review and pull this at your eariliest convinience. I will admit one error that this branch has is that cards will load overlapping, and after loading iframes, it will fix itself. Also, like I said the performance is a slight amount slower, hopefully the angular material ranch fixes this

**Comment by julianpoy** [comment]
I'll do this tonight

**Comment by julianpoy** [comment]
I noticed f0d2e4b. Is this still a viable pull, or should I wait?

**Comment by torch2424** [comment]
Yeah not viable yet, still working on some responsiveness that was broken with increasing the column sizes, to make 2 columns instead of 3 :p

**Comment by torch2424** [comment]
@julianpoy all finished, looking great and good to go! :D

Video (Also in OP):

untitled recording 5

**Comment by julianpoy** [comment]
Beautiful job mate

**Pull request merged**
