### PR TITLE
Usability, Embed Support and more

### PR DESCRIPTION
**Pull request by julianpoy**
This pulls the recent stable updates into production. Updated in this pull are the following:

> Better embed support
> Discontinuation of Embedly
> Responsive styling
> Readability and coloring
> Favicon and site icon
> User input footer

### CODE REVIEW

**Comment by torch2424** [comment]
AWWWEEEE YIIISSSSSSS! :D

**Comment by torch2424** [comment]
Can you put this live for me? <3

**Comment by julianpoy** [comment]
Im already working on it.

**Comment by julianpoy** [comment]
Wait till I create a release for this version

**Comment by torch2424** [comment]
Okay cool thank you! <3

**Pull request merged**
