### PR TITLE
The Great Link Drops Fix

### LINKED ISSUE #79: Make Toasts into a Service
RIght now we are repeating a block of code for a toast, would just be much better to throw into a service, that way we can style and move the toast much easier as well

### LINKED ISSUE #96: Increase Performance
Currently, It takes 1 minute for me to load up my link drops, since I have a lot of drops. We need to find out what is using all of this process.

I think it is the iframe, and I Suggest we simply include a button that will be shown on embeddable links, instead of embedding everything everytime the app opens

### LINKED ISSUE #104: Add really cool animations
It's super easy if you follow the angular ng animate docs:

https://docs.angularjs.org/api/ngAnimate

### PR DESCRIPTION
**Pull request by torch2424**
closes #104 
closes #96 
closes #79 

This does a lot of little fixes, little features such as pagination, and all kinds of crazy animations and hovering. And honestly, makes the app very usable and preety again :)

Ready to be pulled! 

PLEASE TEST EXTENSIVELY! THIS PREETY MUCH IS A FUCTIONALITY REWRITE

### CODE REVIEW

**Comment by torch2424** [comment]
Finally finished up this branch! Please @julianpoy test this out, and let me know what you think. I will admit somethings can act a bit buggy, but it brings insane performance increase, and I feel like they can simply be tweaked.

Also, I cleaned up as much code as I could, and you're better at optimizing code than I am. i bet if you looked through it, it would run even better. but anyways, it'll be a bit buggy, but it's beta, so I think they can be excused for the pull :)

**Comment by torch2424** [comment]
Also I tested this all in chrome, mobile inspector, and my android

**Comment by julianpoy** [comment]
This looks so good. I'll test it now :) :+1: :+1: :+1:

**Comment by julianpoy** [comment]
Amazing! Tons of bugs, but its totally better than what we had before. Like... LIGHT YEARS ahead.

**Pull request merged**
