### PR TITLE
Improve App Performance

### PR DESCRIPTION
**Pull request by torch2424**
Been starting at the code, and followed a couple of guides on how to improve performance in angular apps, specifically this one: http://www.alexkras.com/11-tips-to-improve-angularjs-performance/

Speeds things up a tiny bit, but it's nice!

### CODE REVIEW

**Comment by julianpoy** [comment]
Yo, couple things on this. First off, I removed track by a while ago, because the way we are adding and removing elements in a local scope, track by actually slows things down. Track by uses a local unique id vs angular generating its own. For our purposes, its better to have angular generate it.

I like the one-time bindings! Those are great... Except for labels. Labels need two way binding to work with their sort functions and adding/removal.

Otherwise, dope pull! :dart: on target

**Comment by torch2424** [comment]
Yo But I think track by does the weird finding where all the elements disappear like a machine gun. Can you confirm that? 

And I dont see why using track by would affect adding and deleting int the local scope. but my main point is above.

And fashow I didnt relaize I did that, I did it super fast

**Comment by torch2424** [comment]
Removed watchers on labels. And track by does not do the weird machine gun disappearing, but I find no track by to be actually a bit slower on my end, I was switching back and forth, and track by dump._id was working great for me

**Comment by torch2424** [comment]
Stopwatched several things compared between track by and not track by, track by always felt a little faste, and stop watched show it to be slightly faster

**Comment by torch2424** [comment]
Ill remove track by

**Comment by julianpoy** [comment]
<3

**Comment by torch2424** [comment]
removed track by

**Comment by torch2424** [comment]
Yo I want to avoid conflicts and from what i could tell, track by was your last issue with this branch, going to pull it in. Please odnt blow me up one day in the future for this self pull <3

**Comment by julianpoy** [comment]
:'( I came here to do it for you <3

**Comment by torch2424** [comment]
@julianpoy I'm sorry
selfie-0

**Pull request merged**
